// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNRqiQ-T16tDKHn59iuJqn4w33gjxWSGM',
    appId: '1:136210628183:web:01827084ada246994bad12',
    messagingSenderId: '136210628183',
    projectId: 'home-assigment-be965',
    authDomain: 'home-assigment-be965.firebaseapp.com',
    storageBucket: 'home-assigment-be965.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxGGP8DbnQUjpTYO4uVekdwwAFBhtyNDw',
    appId: '1:136210628183:android:d2cebcb57f9133da4bad12',
    messagingSenderId: '136210628183',
    projectId: 'home-assigment-be965',
    storageBucket: 'home-assigment-be965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfyVJ8nC95mWh0uapO4h7oojpTmU3TlQs',
    appId: '1:136210628183:ios:08a65294eda597dd4bad12',
    messagingSenderId: '136210628183',
    projectId: 'home-assigment-be965',
    storageBucket: 'home-assigment-be965.firebasestorage.app',
    iosBundleId: 'com.example.homeAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfyVJ8nC95mWh0uapO4h7oojpTmU3TlQs',
    appId: '1:136210628183:ios:08a65294eda597dd4bad12',
    messagingSenderId: '136210628183',
    projectId: 'home-assigment-be965',
    storageBucket: 'home-assigment-be965.firebasestorage.app',
    iosBundleId: 'com.example.homeAssigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNRqiQ-T16tDKHn59iuJqn4w33gjxWSGM',
    appId: '1:136210628183:web:bd4641d643ddd6fc4bad12',
    messagingSenderId: '136210628183',
    projectId: 'home-assigment-be965',
    authDomain: 'home-assigment-be965.firebaseapp.com',
    storageBucket: 'home-assigment-be965.firebasestorage.app',
  );
}
